#==============================================================
# Debug mode
#==============================================================
localhost: http://localhost:3000
# debug : true
debug : false


#==============================================================
# Maintain mode
#==============================================================
# maintain : true
maintain : false


#==============================================================
# Administator info
#==============================================================
admin_name: basharbuddha
admin_email: bashar.buddha@gmail.com


#==============================================================
# Site settings
#==============================================================
site_name         : å·´å¤å½±éŸ³è¨Šæ¯åŒ¯é›†
site_title        : å·´å¤å½±éŸ³è¨Šæ¯åŒ¯é›†
site_description  : ğŸ‘½
site_keywords     : é—œéµå­—1,é—œéµå­—2,é—œéµå­—3
site_url          : https://basharbuddha.github.io
og_type           : website
og_image          : https://basharbuddha.github.io/images/fb.jpg
ga_track_id       : UA-169798563-1


#==============================================================
# Facebook APP
#==============================================================
fb_app_id: XXXXXXXXXXXXXXXX
fb_app_version: v2.5


#==============================================================
# Build exclude
#==============================================================
exclude:
  - gulpfile.js
  - package.json
  - node_modules
  - assets


#==============================================================
# Html compress config
#==============================================================
compress_html:
  clippings: all

